version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testingDb
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    # ports:
    #   - 18183:80
    labels:
      - com.codebox.port.phpmyadmin=80
      - com.codebox.port.phpmyadmin.public=false
      - com.codebox.workspace_path=/etc

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server/
     - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    # ports:
    #  - '3000:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
    labels:
      com.codebox.port.grafana: 3000
      com.codebox.port.grafana.public: true

volumes:
  test:
  db_data:
  grafana_storage:
